name: Android Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 安装 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 同意 license
      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # 安装所需 SDK
      - name: Install SDK packages
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # 安装 Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 自动生成 Gradle Wrapper（修复缺失 jar 问题）
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      # 给权限
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 构建
      - name: Build Release
        run: ./gradlew assembleRelease --no-daemon

      # 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OplusKeyHook
          path: app/build/outputs/**/*.apk
